//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ClientService = new HashSet<ClientService>();
            this.ServicePhoto = new HashSet<ServicePhoto>();
        }
    
        public int ID { get; set; }

      

        public string Title { get; set; }
        public decimal cost;
        public decimal Cost
        {
            get { return cost; }
            set { cost = value; }
        }
        [NotMapped]
        public decimal CostDisc
        {
            get { if (Discount == null) return cost; else { return cost - (cost * ((decimal)Discount / 100)); } }
            set { cost = value; }
           
        }
        public int duration;
        public int DurationInSeconds
        {
            get { return duration / 60; }
            set { duration = value; }
        }


        public string Description { get; set; }
        public Nullable<double> discount;
        public Nullable<double> Discount { get { return discount * 100; } set { discount = value; } }
        public string mainImage;
        public string MainImagePath {
            get { return mainImage; }
            set { mainImage = value; } 
        }
        [NotMapped]
        public string mainImagePathsp
        {
            get { return "pack://siteoforigin:,,,/" + mainImage; }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhoto { get; set; }
    }
}
