//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salon.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ServicePhoto
    {
        public int ID { get; set; }
        public int ServiceID { get; set; }
        public string photoPath;
        public string PhotoPath
        {
            get
            {
                return photoPath;
            }
            set
            {
                photoPath = value;
            }
        }

        [NotMapped]
        public string PhotoPathSet
        {
            get
            {
                return "pack://siteoforigin:,,,/" + photoPath;
            }
        }

        public virtual Service Service { get; set; }
    }
}
